name: automated_work_control

version: 1.0.0+1A

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  pattern_formatter: ^2.0.0
  bloc: ^8.0.3
  dio: ^4.0.0
  easy_localization: ^3.0.0
  equatable: ^2.0.0
  floor: ^1.1.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  logger: ^1.0.0
  hydrated_bloc: ^8.0.0
  flutter_screenutil: ^5.4.0+1
  bot_toast: ^4.0.1
  auto_size_text: ^3.0.0
  flutter_svg: ^1.0.3
  super_rich_text: ^1.0.0
  simple_gradient_text: ^1.2.2
  connectivity_plus: ^2.3.3
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^3.0.1
  dotted_border: ^2.0.0+2
  flutter_spinkit: ^5.1.0
  pie_chart: ^5.3.2
  charts_painter: ^2.0.0+2
  simple_ripple_animation: ^0.0.3
  cached_network_image: ^3.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter
  build_runner: ^2.1.0
  floor_generator: ^1.1.0
  import_sorter: ^4.4.2
  lint: ^1.5.3
  flutter_launcher_icons: ^0.9.2
  image_picker: ^0.8.5+3
  package_info_plus: ^1.4.2
#  flutter_native_splash: ^2.2.3
#  titled_navigation_bar: ^5.0.0-nullsafety.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/langs/
    - assets/icons/
    - assets/images/
    - assets/fonts/

import_sorter:
  emojis: true
  ignored_files:
    - \/*.g.dart\/*


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"